web/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "web"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    # path("about/", TemplateView.as_view(template_name="web/about.html"), name="about"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    # policy
    path(
        "privacy-policy/",
        TemplateView.as_view(template_name="web/privacy_policy.html"),
        name="privacy_policy",
    ),
    path(
        "terms-conditions/",
        TemplateView.as_view(template_name="web/terms_conditions.html"),
        name="terms_conditions",
    ),
    path(
        "refund-policy/",
        TemplateView.as_view(template_name="web/refund_policy.html"),
        name="refund_policy",
    ),
    path(
        "shipping-policy/",
        TemplateView.as_view(template_name="web/shipping_policy.html"),
        name="shipping_policy",
    ),
    path(
        "contact-policy/",
        TemplateView.as_view(template_name="web/contact_policy.html"),
        name="contact_policy",
    ),
    # shop
    path("shop/", views.ShopView.as_view(), name="shop"),
    path(
        "product-detail/<slug:slug>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path("whatsapp-order/", views.order, name="order"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("get_shipping_fee/", views.get_shipping_fee, name="get_shipping_fee"),
    # CART
    path("shop/cart/", views.cart_view, name="cart"),
    path("shop/cart/add/", views.cart_add, name="add_cart"),
    path(
        "shop/cart-item-clear/<str:item_id>/",
        views.clear_cart_item,
        name="clear_cart_item",
    ),
    path("shop/cart-minus/", views.minus_to_cart, name="minus_to_cart"),
    path("shop/cart-clear/", views.clear_cart, name="clear_cart"),
    # payment
    path("payment/<str:pk>/", views.PaymentView.as_view(), name="payment"),
    path("callback/<str:pk>/", views.callback, name="callback"),
    path(
        "complete-order/<str:pk>/",
        views.CompleteOrderView.as_view(),
        name="complete_order",
    ),
    path(
        "user/order/<str:order_id>/detail/",
        views.UserOrderDetailView.as_view(),
        name="order_detail",
    ),

    path("wishlist/", views.WishlistListView.as_view(), name="wishlist"),
    path("wishlist/add/",views.AddToWishlistView.as_view(),name="add_to_wishlist"),
    path("shop/wishlist/remove/<int:product_id>/",views.RemoveFromWishlistView.as_view(),name="remove_from_wishlist"),
    # path('my-account/',views.MyAccountView.as_view() ,name='my-account'),
    path('my-orders/',views.MyOrderView.as_view() ,name='my_orders'),
    # path('order-details/<int:pk>/',views.MyOrderDetailsView.as_view() ,name='order_detail'),
    
    path('search-autocomplete/',views.AutocompleteView.as_view(), name='search-autocomplete'),

path("error/", views.error, name="error"),
]

xyra/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls', namespace='web'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/web/partials/footer.html
{% load static %}

<footer class="pt-14 pt-lg-20 pb-16 footer bg-body-tertiary">
    <div class="container pt-4">
      <div class="row">
        <div class="col-lg-5 col-12 mb-12 mb-lg-0">
          <h3 class="mb-6">
            Care for Your Skin, <br />
            Care for Your Beauty
          </h3>
          <p class="pe-xl-23 mb-lg-11">
            Smile with the reflection of the glow. Let your Skin define your
            age and not the years
          </p>
          <a
            class="fw-semibold fs-6 text-decoration-none"
            href="https://templates.g5plus.net/find-a-store.html"
          >
            Find a store
            <svg class="icon ms-5">
              <use xlink:href="#icon-arrow-right"></use>
            </svg>
          </a>
        </div>
        <div class="col-lg col-md-4 col-12 mb-11 mb-lg-0">
          <h3 class="fs-5 mb-6">Company</h3>

          <ul class="list-unstyled mb-0 fw-medium">
            <li class="pt-3 mb-4">
              <a href="#" title="About us" class="text-body">About us</a>
            </li>

            <li class="pt-3 mb-4">
              <a href="#" title="Careers" class="text-body">Careers</a>
            </li>

            <li class="pt-3 mb-4">
              <a href="#" title="Store Locations" class="text-body"
                >Store Locations</a
              >
            </li>

            <li class="pt-3 mb-4">
              <a href="#" title="Our Blog" class="text-body">Our Blog</a>
            </li>

            <li class="pt-3 mb-4">
              <a href="#" title="Reviews" class="text-body">Reviews</a>
            </li>
          </ul>
        </div>
        <div class="col-lg col-md-4 col-12 mb-11 mb-lg-0">
          <h3 class="fs-5 mb-6">Useful links</h3>

          <ul class="list-unstyled mb-0 fw-medium">
            <li class="pt-3 mb-4">
              <a href="#" title="New Products" class="text-body"
                >New Products</a
              >
            </li>

            <li class="pt-3 mb-4">
              <a href="#" title="Best Sellers" class="text-body"
                >Best Sellers</a
              >
            </li>

            <li class="pt-3 mb-4">
              <a href="#" title="Bundle &amp; Save" class="text-body"
                >Bundle &amp; Save</a
              >
            </li>

            <li class="pt-3 mb-4">
              <a href="#" title="Online Gift Card" class="text-body"
                >Online Gift Card</a
              >
            </li>
          </ul>
        </div>
        <div class="col-lg col-md-4 col-12 mb-12 mb-lg-0">
          <h3 class="fs-5 mb-6">Information</h3>

          <ul class="list-unstyled mb-0 fw-medium">
            <li class="pt-3 mb-4">
              <a href="#" title="Start a Return" class="text-body"
                >Start a Return</a
              >
            </li>

            <li class="pt-3 mb-4">
              <a href="#" title="Contact Us" class="text-body">Contact Us</a>
            </li>

            <li class="pt-3 mb-4">
              <a href="#" title="Shipping FAQ" class="text-body"
                >Shipping FAQ</a
              >
            </li>

            <li class="pt-3 mb-4">
              <a href="#" title="Terms &amp; Conditions" class="text-body"
                >Terms &amp; Conditions</a
              >
            </li>

            <li class="pt-3 mb-4">
              <a href="#" title="Privacy Policy" class="text-body"
                >Privacy Policy</a
              >
            </li>
          </ul>
        </div>
      </div>
      <div class="row align-items-center mt-0 mt-lg-20 pt-lg-4">
        <div
          class="col-sm-12 col-md-6 col-lg-4 d-flex align-items-center order-2 order-lg-1 fs-6 mt-11 mt-lg-0"
        >
          <p class="mb-0">© Glowing 2023</p>
          <ul class="list-inline fs-18px ms-6 mb-0">
            <li class="list-inline-item me-8">
              <a href="#"><i class="fab fa-twitter"></i></a>
            </li>
            <li class="list-inline-item me-8">
              <a href="#"><i class="fab fa-facebook-f"></i></a>
            </li>
            <li class="list-inline-item me-8">
              <a href="#"><i class="fab fa-instagram"></i></a>
            </li>
            <li class="list-inline-item">
              <a href="#"><i class="fab fa-youtube"></i></a>
            </li>
          </ul>
        </div>
        <div class="col-sm-12 col-lg-4 text-md-center order-1 order-lg-2">
          <a class="d-inline-block" href="index.html">
            <img
              class="lazy-image img-fluid light-mode-img"
              src="#"
              data-src="{% static 'web\images\others\xyra-logo.webp' %}"
              width="179"
              height="26"
              alt="Glowing - Bootstrap 5 HTML Templates"
            />

          </a>
        </div>
        <div
          class="col-sm-12 col-md-6 col-lg-4 order-3 text-sm-start text-lg-end mt-11 mt-lg-0"
        >
          <img
            src="#"
            data-src="{% static 'web/images/footer/img_1.png' %}"
            width="313"
            height="28"
            alt="Paypal"
            class="img-fluid lazy-image"
          />
        </div>
      </div>
    </div>
  </footer>

templates/web/partials/header.html
{% load static %}
<header
  id="header"
  class="header header-sticky z-index-5 header-sticky-smart disable-transition-all position-absolute start-0 end-0"
>
  <div class="sticky-area">
    <div
      class="main-header nav navbar navbar-light navbar-expand-xl py-6 py-xl-0"
    >
      <div class="container-wide container flex-nowrap px-10">
        <div class="w-50px d-flex d-xl-none">
          <button
            class="navbar-toggler align-self-center border-0 shadow-none px-0 canvas-toggle p-4"
            type="button"
            data-bs-toggle="offcanvas"
            data-bs-target="#offCanvasNavBar"
            aria-controls="offCanvasNavBar"
            aria-expanded="false"
            aria-label="Toggle Navigation"
          >
            <span class="fs-24 toggle-icon"></span>
          </button>
        </div>

        <a
          href="#"
          class="navbar-brand has-sticky-logo py-4 mx-auto w-xl-50"
        >
          <img
            class="light-mode-img "
            src="{% static 'web\images\others\xyra-logo.webp' %}"
            width="90"
            height="60"
            alt="Glowing - Bootstrap 5 HTML Templates"/>
          
          
          </a>

        <div class="d-none d-xl-flex w-xl-70">
          <ul class="navbar-nav">
            <li class="nav-item transition-all-xl-1 py-xl-11 py-0 me-xxl-12 me-xl-10">
              <a
                class="nav-link d-flex justify-content-between position-relative py-xl-0 px-xl-0 text-uppercase fw-semibold ls-1 fs-15px fs-xl-14px"
                href="{% url "web:index" %}"
                id="menu-item-home"
              >
                Home
              </a>
            </li>
            <li class="nav-item transition-all-xl-1 py-xl-11 py-0 me-xxl-12 me-xl-10">
              <a
                class="nav-link d-flex justify-content-between position-relative py-xl-0 px-xl-0 text-uppercase fw-semibold ls-1 fs-15px fs-xl-14px"
                href="{% url "web:about" %}"
                id="menu-item-about"
              >
                About Us
              </a>
            </li>
            <li class="nav-item transition-all-xl-1 py-xl-11 py-0 me-xxl-12 me-xl-10">
              <a
                class="nav-link d-flex justify-content-between position-relative py-xl-0 px-xl-0 text-uppercase fw-semibold ls-1 fs-15px fs-xl-14px"
                href="{% url "web:shop" %}"
                id="menu-item-products"
              >
                Products
              </a>
            </li>
            <li class="nav-item transition-all-xl-1 py-xl-11 py-0 me-xxl-12 me-xl-10">
              <a
                class="nav-link d-flex justify-content-between position-relative py-xl-0 px-xl-0 text-uppercase fw-semibold ls-1 fs-15px fs-xl-14px"
                href="{% url "web:contact" %}"
                id="menu-item-contact"
              >
                Contact Us
              </a>
            </li>
          </ul>
          
        </div>
        <div
          class="icons-actions d-flex justify-content-end w-xl-50 fs-28px text-body-emphasis"
        >
          <div class="px-xl-5 d-inline-block">
            <a
              class="lh-1 color-inherit text-decoration-none"
              href="#"
              data-bs-toggle="offcanvas"
              data-bs-target="#searchModal"
              aria-controls="searchModal"
              aria-expanded="false"
            >
              <svg class="icon icon-magnifying-glass-light">
                <use xlink:href="#icon-magnifying-glass-light"></use>
              </svg>
            </a>
          </div>
          <div class="px-5 d-none d-xl-inline-block">
            <a
              class="lh-1 color-inherit text-decoration-none"
              href="#"
              data-bs-toggle="modal"
              data-bs-target="#signInModal"
            >
              <svg class="icon icon-user-light">
                <use xlink:href="#icon-user-light"></use>
              </svg>
            </a>
          </div>
          <div class="px-5 d-none d-xl-inline-block">
            <a
              class="position-relative lh-1 color-inherit text-decoration-none"
              href="shop/wishlist.html"
            >
              <svg class="icon icon-star-light">
                <use xlink:href="#icon-star-light"></use>
              </svg>
              <span
                class="badge bg-dark text-white position-absolute top-0 start-100 translate-middle mt-4 rounded-circle fs-13px p-0 square"
                style="--square-size: 18px"
                >3</span
              >
            </a>
          </div>
          <div class="px-5 d-none d-xl-inline-block">
            <a
              class="position-relative lh-1 color-inherit text-decoration-none"
              href="#"
              data-bs-toggle="offcanvas"
              data-bs-target="#shoppingCart"
              aria-controls="shoppingCart"
              aria-expanded="false"
            >
              <svg class="icon icon-star-light">
                <use xlink:href="#icon-shopping-bag-open-light"></use>
              </svg>
              <span
                class="badge bg-dark text-white position-absolute top-0 start-100 translate-middle mt-4 rounded-circle fs-13px p-0 square"
                style="--square-size: 18px"
                >3</span
              >
            </a>
          </div>

          
        </div>
      </div>
    </div>
  </div>

  <div class="navbar">
    <div
      id="offCanvasNavBar"
      class="offcanvas offcanvas-start"
      style="--bs-offcanvas-width: 310px"
    >
      <div class="offcanvas-header bg-body-tertiary">
        <img class="lazy-image img-fluid light-mode-img" src="" data-src="{% static "web/images/others/xyra-logo.webp" %}" width="70" height="5" alt="Glowing - Bootstrap 5 HTML Templates">
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="offcanvas"
          aria-label="Close"
        ></button>
      </div>
      <hr class="mt-0" />
      <div class="offcanvas-body pt-0 mb-2">
        <ul class="navbar-nav">
          <li
            class="nav-item transition-all-xl-1 py-0 dropdown dropdown-fullwidth"
          >
            <a
              class="nav-link d-flex justify-content-between position-relative text-uppercase fw-semibold ls-1 fs-15px "
              href="#"
              
              id="menu-item-home-canvas"
              aria-haspopup="true"
              aria-expanded="false"
              >Home</a
            >
            
          </li>
          
          <li class="nav-item transition-all-xl-1 py-0 dropdown">
            <a
              class="nav-link d-flex justify-content-between position-relative text-uppercase fw-semibold ls-1 fs-15px "
              href="#"
              
              id="menu-item-pages-canvas"
              aria-haspopup="true"
              aria-expanded="false"
              >About Us</a
            >
            
          </li>
          <li
            class="nav-item transition-all-xl-1 py-0 dropdown dropdown-fullwidth"
          >
            <a
              class="nav-link d-flex justify-content-between position-relative text-uppercase fw-semibold ls-1 fs-15px "
              href="#"
              
              id="menu-item-blocks-canvas"
              aria-haspopup="true"
              aria-expanded="false"
              >Products</a
            >
            <li
            class="nav-item transition-all-xl-1 py-0 dropdown dropdown-fullwidth"
          >
            <a
              class="nav-link d-flex justify-content-between position-relative text-uppercase fw-semibold ls-1 fs-15px "
              href="#"
              
              id="menu-item-home-canvas"
              aria-haspopup="true"
              aria-expanded="false"
              >Blogs</a
            >
            
          </li>
          </li>
          <li
            class="nav-item transition-all-xl-1 py-0 dropdown dropdown-fullwidth"
          >
            <a
              class="nav-link d-flex justify-content-between position-relative text-uppercase fw-semibold ls-1 fs-15px "
              href="#"
              
              id="menu-item-docs-canvas"
              aria-haspopup="true"
              aria-expanded="false"
              >Contact Us</a
            >
            
          </li>
        </ul>
      </div>
      <hr class="mb-0" />
      <div class="offcanvas-footer bg-body-tertiary">
        © 2023 Glowing. <br />
        All rights reserved.
      </div>
    </div>
  </div>
</header>